### ISSUE TITLE
Contribution && aide

### ISSUE THREAD

**Issue by mariogamer2** [Ginkyway/Guide#1]
Salut...

Premièrement, bravo, tu as finis la traduction avant moi XD

Deuxièmement,je voudrais savoir si je pourrais aider à mettre à jour le tutoriel et à créé des forums d'aides sur logic-sunrise et gamergen.

T'inquiète pas,je suis pas du genre à me procurer les tutoriels XD.

**Comment by Ginkyway** [comment]
Salut,

Bien sûr, je ne suis pas très au courant à propos des communautés françaises donc ça aiderait beaucoup.

Pour la mise à jour, j'entends suivre de très près les modifications que Plailect apporte à son guide donc je ne pense pas avoir besoin d'aide de ce côté-là, mais s'il y aurait des changements pertinents à faire à certains endroits, je suis très ouvert sur cet aspect.

**Comment by mariogamer2** [comment]
Faudrait t'inscrire à logic-sunrise.com ,ca nous permettrai d'aider les gens...

@HoloryTV Pourrait aussi nous aider.

**Comment by mariogamer2** [comment]
PS. Pour ajouter un contributeur:

Settings -> Collaborators  (settings dans la barre d'onglet, puis collaborators dans la barre de gauche)

**Comment by HoloryTV** [comment]
Bonjour à vous deux, que puis-je pour vous ?

**Comment by mariogamer2** [comment]
Faudrait etre plus que 1 pour géré le forum que je viens de lier...

En passant,pourrait tu me dire si le forum est pas mal?

**Comment by HoloryTV** [comment]
Je ne suis pas encore très familiarisé avec Github de même pour Logic-Sunrise.

Tu parles de ça ? : http://www.logic-sunrise.com/forums/topic/72276-le-guide-vfr-downgrade-rednand-downgrade/#entry856910

Parce que ce n'est pas un forum mais une discussion qu'est-ce que tu voudrais ajouter de plus dessus ?

**Comment by mariogamer2** [comment]
Je demande tn avis pour voir si je pourrais l'améliorer.

**Comment by HoloryTV** [comment]
Ce que je mets entre parenthèse est à enlever.
Ce que je mets entre crochet est à rajouter/changer.

1. vous avez des chances de brick(er)
2. Ni moi, ni Ginkyway ne pourr[ont] être accusé(e)!!!
3. Ceci est un forum d'aide,donc voici quelque[s] règle[s] à respecter
4. Assurez-vous d'avoir bien suivi(e) les étapes avant de vous plaindre(s)! : 
    - Bien décrire le problème rencontré 
    - S'assurer que le problème c'est pas déjà répertorié ici
    - Un bonjour merci et au revoir n'est jamais de trop ;)
    - Le lien de la traduction : https://github.com/G...de/wiki/Accueil

**Comment by mariogamer2** [comment]
Je l'ais déja mis le lien :)

Merci

**Comment by HoloryTV** [comment]
Oui je te propose juste une autre façon de présenter ton texte ;)

**Comment by mariogamer2** [comment]
@Ginkyway Alors?

**Comment by Ginkyway** [comment]
Je préfère rester le seul à pouvoir modifier le guide, il y a toujours la section Issues que je vérifie régulièrement pour les propositions de changements.

**Comment by mariogamer2** [comment]
Ok

**Comment by mariogamer2** [comment]
Je ne peux vraiment pas aider?

**Comment by mariogamer2** [comment]
Je serais bien plus libre dans pas longtemps,et à ce que je vois,il y as plusieurs commit de différence...

Si tu as besoin d'aide...
