### ISSUE TITLE
Merci pour la traduction du guide

### ISSUE THREAD

**Issue by Aludark88** [Ginkyway/Guide#2]
Merci pour la traduction de ce guide, qui et très claire :) j'ai réussi toutes les étapes sans aucuns soucis ! Cependant j'ai relevé 2 anomalies sur le guide:

1er:

https://github.com/Ginkyway/Guide/wiki/Partie-4-%28Obtenir-l'OTP%29

Etape 26: (Vos backups doivent correspondre à l'une des tailles sur cette page; si ce n'est pas le cas, vous devez les supprimer et en faire d'autres !)

il n'y a pas le lien cliquable pour le tableau.

2 éme:

https://github.com/Ginkyway/Guide/wiki/Partie-5-%28arm9loaderhax-&-Luma3DS%29

Section V - Enlever RedNAND de la carte SD

Je pense que tu pourrait ajouté une étape 10 Remettre la carte sd dans la console

Pour toi c'est peut être anodin, mais pour les utilisateur lambda peut être moins ^^

Merci encore !

**Comment by mariogamer2** [comment]
Lol....

1.  https://github.com/Ginkyway/Guide/wiki/Taille-du-NAND

2.  Pas besoin????

**Comment by Ginkyway** [comment]
Merci pour tes commentaires ! Ça fait plaisir.

#1 - En effet, le lien est manquant, certainement un oubli. Je corrige tout de suite.

#2 - L'étape n'était pas présente dans le guide original et je préfère rester le plus fidèle possible à cette version, par contre le changement me semble pertinent. Je vais le rapporter à Plailect, voir s'il apporte les correctifs nécessaires puis je corrigerai la traduction en conséquence.

**Comment by Ginkyway** [comment]
Partie 5 corrigée.

**Comment by kaiomar** [comment]
je me permets de poster ici car je ne comprend rien à ce site :p 
Partie 5, Section 6 et étape 2 : "Toujours à partir d'EmuNAND" 
tu as en fait oublié le 9 apres EmuNAND.
voila voila et merci pour la traduction !

**Comment by Ginkyway** [comment]
C'est corrigé, merci!
