### ISSUE TITLE
Transférer REDNAND vers nouvelle SD ( Partie 4 )

### ISSUE THREAD

**Issue by Erulak** [Ginkyway/Guide#3]
Bonjour, j'en suis à la Partie 4 - Section II du tuto et au moment du backup, ma carte sd de 2go ne dispose pas d'assez d'espace pour procéder au backup ni de REDNAND ni de SYSNAND, j'ai donc commandé une carte de 64go, comment transférer mes données dessus et reprendre là où j'en étais ? Merci.

**Comment by Ginkyway** [comment]
Bonjour. Tu as raison de poser cette question, la présence d'un RedNAND complique un peu la chose.

J'ai personnellement utilisé [ce guide](https://gbatemp.net/threads/how-to-transfer-emunand-to-another-sd-card-working-on-new3ds.383684/) pour accomplir cette tâche. En gros, on crée une image (backup) de la carte SD contenant toutes les partitions (dont la partition RedNAND) puis on la restaure vers la nouvelle carte SD en redimensionnant pour prendre en compte sa nouvelle taille.

Ce lien est en anglais mais le processus n'est ni long ni très compliqué, cependant si tu en as besoin demande-le et je peux en effectuer une traduction sommaire.

**Comment by Erulak** [comment]
Merci beaucoup, j'avais trouvé ce guide mais impossible de redimensionner la partition de la carte sd sans la corrompre, ni avec easeus, ni avec gparted.. Du coup j'ai simplement recommencé la manip au début de la partie 3 et ça a marché ! Merci pour tout :)
