### ISSUE TITLE
Impossible de lancer Decrypt9

### ISSUE THREAD

**Issue by alexm92300** [Ginkyway/Guide#5]
Bonjour !

Je suis arrivé au point 11 de la section II, mais impossible de lancer Decrypt9, ca me fait écran rouge/noir/Rouge puis retour au Homebrew ... j'ai peut être mal installé les dossiers ? (D'ailleurs je trouve qu'à chaque fois il y à énormement de différence entre le contenu du zip et ce que vous demandez de transferer ... j'ai perdu pas mal de temps a comprendre xD)

pour info mon RedNand est en 11.3.0-36E et mon SysNand est en 9.2.0-20E

heeelp plz :D

**Comment by alexm92300** [comment]
Bon j'ai réussi après 30 min de galère en utilisant la version inferieur de Decrypt9WIP

Par contre je viens de re-perdre 30min sur le point 17 car vous avez dit de copier le fichier sur la racine SD ... et que Decrypt9WIP fonctionne sur le dossier Files9 ... c'est marqué en blanc sur noir en bas .. c'est con de perdre du temps là dessus :/ (Je critique pas le tuto hein, c'est fantastique le boulot fait, mais des imprécisions comme ça, c'est comme quand le médécin te fait ton ordonnance puis il a tellement mal gribouillé que tu sais pas ce que tu dois prendre et quand xD)

**Comment by Ginkyway** [comment]
Ma version du guide est extrêmement obsolète, il vaudrait mieux arrêter tout de suivre et suivre celui-ci à la place: https://3ds.guide/

(je ne sais pas s'il est disponible en français par contre)
